// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module packet_handler_packet_identification (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_TVALID,
        eth_level_pkt_din,
        eth_level_pkt_num_data_valid,
        eth_level_pkt_fifo_cap,
        eth_level_pkt_full_n,
        eth_level_pkt_write,
        start_out,
        start_write,
        s_axis_TDATA,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST,
        s_axis_TDEST
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   s_axis_TVALID;
output  [1023:0] eth_level_pkt_din;
input  [4:0] eth_level_pkt_num_data_valid;
input  [4:0] eth_level_pkt_fifo_cap;
input   eth_level_pkt_full_n;
output   eth_level_pkt_write;
output   start_out;
output   start_write;
input  [511:0] s_axis_TDATA;
output   s_axis_TREADY;
input  [63:0] s_axis_TKEEP;
input  [63:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;
input  [2:0] s_axis_TDEST;

reg ap_done;
reg ap_idle;
reg[1023:0] eth_level_pkt_din;
reg eth_level_pkt_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    internal_ap_ready;
wire   [0:0] grp_nbreadreq_fu_94_p7;
reg    ap_predicate_op14_read_state1;
reg    ap_predicate_op25_read_state1;
reg    ap_predicate_op33_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] pi_fsm_state_load_reg_323;
reg   [0:0] tmp_2_reg_327;
reg    ap_predicate_op59_write_state2;
reg   [0:0] tmp_reg_342;
reg   [15:0] ethernetType_V_reg_351;
reg   [7:0] ipProtocol_V_reg_355;
reg   [0:0] icmp_ln1019_reg_359;
reg    ap_predicate_op64_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] pi_fsm_state;
reg   [1:0] tdest_r_V;
reg    s_axis_TDATA_blk_n;
reg    eth_level_pkt_blk_n;
reg   [511:0] reg_179;
reg   [63:0] reg_183;
wire   [0:0] grp_fu_175_p1;
reg   [0:0] tmp_last_V_1_reg_331;
reg   [0:0] tmp_last_V_reg_346;
wire   [15:0] ethernetType_V_fu_223_p3;
wire   [7:0] ipProtocol_V_fu_241_p4;
wire   [0:0] icmp_ln1019_fu_251_p2;
reg   [1:0] ap_phi_mux_storemerge_i_phi_fu_134_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_131;
wire   [1:0] ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_142;
reg   [1:0] ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142;
wire   [1:0] select_ln235_fu_263_p3;
wire   [1023:0] zext_ln248_fu_294_p1;
wire   [1023:0] zext_ln228_fu_318_p1;
wire   [7:0] tmp_5_i_fu_213_p4;
wire   [7:0] tmp_4_i_fu_203_p4;
wire   [3:0] ipVersion_V_fu_231_p4;
wire   [585:0] tmp_6_i_fu_281_p6;
wire   [585:0] tmp_7_i_fu_305_p6;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    regslice_both_s_axis_V_data_V_U_apdone_blk;
wire   [511:0] s_axis_TDATA_int_regslice;
wire    s_axis_TVALID_int_regslice;
reg    s_axis_TREADY_int_regslice;
wire    regslice_both_s_axis_V_data_V_U_ack_in;
wire    regslice_both_s_axis_V_keep_V_U_apdone_blk;
wire   [63:0] s_axis_TKEEP_int_regslice;
wire    regslice_both_s_axis_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_V_strb_V_U_apdone_blk;
wire   [63:0] s_axis_TSTRB_int_regslice;
wire    regslice_both_s_axis_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_TLAST_int_regslice;
wire    regslice_both_s_axis_V_last_V_U_vld_out;
wire    regslice_both_s_axis_V_last_V_U_ack_in;
wire    regslice_both_s_axis_V_dest_V_U_apdone_blk;
wire   [2:0] s_axis_TDEST_int_regslice;
wire    regslice_both_s_axis_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_V_dest_V_U_ack_in;
reg    ap_condition_218;
reg    ap_condition_244;
reg    ap_condition_246;
reg    ap_condition_248;
reg    ap_condition_398;
reg    ap_condition_241;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 pi_fsm_state = 2'd0;
#0 tdest_r_V = 2'd0;
end

packet_handler_regslice_both #(
    .DataWidth( 512 ))
regslice_both_s_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_TDATA),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_data_V_U_ack_in),
    .data_out(s_axis_TDATA_int_regslice),
    .vld_out(s_axis_TVALID_int_regslice),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_data_V_U_apdone_blk)
);

packet_handler_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_TKEEP),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_keep_V_U_ack_in),
    .data_out(s_axis_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_V_keep_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_keep_V_U_apdone_blk)
);

packet_handler_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_TSTRB),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_strb_V_U_ack_in),
    .data_out(s_axis_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_V_strb_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_strb_V_U_apdone_blk)
);

packet_handler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_TLAST),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_last_V_U_ack_in),
    .data_out(s_axis_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_V_last_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_last_V_U_apdone_blk)
);

packet_handler_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_TDEST),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_dest_V_U_ack_in),
    .data_out(s_axis_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_V_dest_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_398)) begin
        if ((1'b1 == ap_condition_248)) begin
            ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142 <= 2'd1;
        end else if ((1'b1 == ap_condition_246)) begin
            ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142 <= 2'd2;
        end else if ((1'b1 == ap_condition_244)) begin
            ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142 <= 2'd3;
        end else if ((1'b1 == ap_condition_218)) begin
            ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142 <= 2'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142 <= ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_142;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        pi_fsm_state <= select_ln235_fu_263_p3;
    end else if (((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (pi_fsm_state == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_175_p1 == 1'd1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (pi_fsm_state == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_175_p1 == 1'd1)))) begin
        pi_fsm_state <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & ((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~(ethernetType_V_fu_223_p3 == 16'd2054) & ~(ethernetType_V_fu_223_p3 == 16'd2048) & (grp_nbreadreq_fu_94_p7 == 1'd1)) | (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~(ethernetType_V_fu_223_p3 == 16'd2054) & ~(ipProtocol_V_fu_241_p4 == 8'd1) & ~(ipProtocol_V_fu_241_p4 == 8'd6) & ~(ipProtocol_V_fu_241_p4 == 8'd17) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (icmp_ln1019_fu_251_p2 == 1'd1))))) begin
        tdest_r_V <= 2'd3;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2) & (((((~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (ipProtocol_V_reg_355 == 8'd6)) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (ipProtocol_V_reg_355 == 8'd17))) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (ipProtocol_V_reg_355 == 8'd1))) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (icmp_ln1019_reg_359 == 1'd0))) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2054) & (tmp_reg_342 == 1'd1))))) begin
        tdest_r_V <= ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142;
    end
end

always @ (posedge ap_clk) begin
    if ((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ethernetType_V_reg_351 <= ethernetType_V_fu_223_p3;
        ipProtocol_V_reg_355 <= {{s_axis_TDATA_int_regslice[191:184]}};
        tmp_last_V_reg_346 <= s_axis_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ethernetType_V_fu_223_p3 == 16'd2048))) begin
        icmp_ln1019_reg_359 <= icmp_ln1019_fu_251_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        pi_fsm_state_load_reg_323 <= pi_fsm_state;
    end
end

always @ (posedge ap_clk) begin
    if (((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (pi_fsm_state == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        reg_179 <= s_axis_TDATA_int_regslice;
        reg_183 <= s_axis_TKEEP_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (pi_fsm_state == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_2_reg_327 <= grp_nbreadreq_fu_94_p7;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (pi_fsm_state == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_last_V_1_reg_331 <= s_axis_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_reg_342 <= grp_nbreadreq_fu_94_p7;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~(ethernetType_V_fu_223_p3 == 16'd2054) & ~(ethernetType_V_fu_223_p3 == 16'd2048) & (grp_nbreadreq_fu_94_p7 == 1'd1)) | (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & ~(ethernetType_V_fu_223_p3 == 16'd2054) & ~(ipProtocol_V_fu_241_p4 == 8'd1) & ~(ipProtocol_V_fu_241_p4 == 8'd6) & ~(ipProtocol_V_fu_241_p4 == 8'd17) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (icmp_ln1019_fu_251_p2 == 1'd1)))) begin
        ap_phi_mux_storemerge_i_phi_fu_134_p4 = 2'd2;
    end else if ((((((~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (ipProtocol_V_fu_241_p4 == 8'd6) & (ethernetType_V_fu_223_p3 == 16'd2048)) | (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (ipProtocol_V_fu_241_p4 == 8'd17) & (ethernetType_V_fu_223_p3 == 16'd2048))) | (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (ipProtocol_V_fu_241_p4 == 8'd1) & (ethernetType_V_fu_223_p3 == 16'd2048))) | (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (icmp_ln1019_fu_251_p2 == 1'd0) & (ethernetType_V_fu_223_p3 == 16'd2048))) | (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (ethernetType_V_fu_223_p3 == 16'd2054)))) begin
        ap_phi_mux_storemerge_i_phi_fu_134_p4 = 2'd1;
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_134_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_131;
    end
end

always @ (*) begin
    if ((((ap_predicate_op59_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op64_write_state2 == 1'b1)))) begin
        eth_level_pkt_blk_n = eth_level_pkt_full_n;
    end else begin
        eth_level_pkt_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_241)) begin
        if ((ap_predicate_op64_write_state2 == 1'b1)) begin
            eth_level_pkt_din = zext_ln228_fu_318_p1;
        end else if ((ap_predicate_op59_write_state2 == 1'b1)) begin
            eth_level_pkt_din = zext_ln248_fu_294_p1;
        end else begin
            eth_level_pkt_din = 'bx;
        end
    end else begin
        eth_level_pkt_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (ap_predicate_op59_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op64_write_state2 == 1'b1)))) begin
        eth_level_pkt_write = 1'b1;
    end else begin
        eth_level_pkt_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (ap_predicate_op33_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (ap_predicate_op25_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (ap_predicate_op14_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1)))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID_int_regslice;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (ap_predicate_op33_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (ap_predicate_op25_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (ap_predicate_op14_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        s_axis_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0))) & ~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_condition_218 = (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (ethernetType_V_fu_223_p3 == 16'd2054));
end

always @ (*) begin
    ap_condition_241 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

always @ (*) begin
    ap_condition_244 = (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (icmp_ln1019_fu_251_p2 == 1'd1) & (ipProtocol_V_fu_241_p4 == 8'd17) & (ethernetType_V_fu_223_p3 == 16'd2048));
end

always @ (*) begin
    ap_condition_246 = (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (icmp_ln1019_fu_251_p2 == 1'd1) & (ipProtocol_V_fu_241_p4 == 8'd6) & (ethernetType_V_fu_223_p3 == 16'd2048));
end

always @ (*) begin
    ap_condition_248 = (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1) & (icmp_ln1019_fu_251_p2 == 1'd1) & (ipProtocol_V_fu_241_p4 == 8'd1) & (ethernetType_V_fu_223_p3 == 16'd2048));
end

always @ (*) begin
    ap_condition_398 = (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op33_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op25_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op14_read_state1 == 1'b1) & (s_axis_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op59_write_state2 == 1'b1) & (eth_level_pkt_full_n == 1'b0)) | ((eth_level_pkt_full_n == 1'b0) & (ap_predicate_op64_write_state2 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_storemerge_i_reg_131 = 'bx;

assign ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_142 = 'bx;

always @ (*) begin
    ap_predicate_op14_read_state1 = ((grp_nbreadreq_fu_94_p7 == 1'd1) & (pi_fsm_state == 2'd1));
end

always @ (*) begin
    ap_predicate_op25_read_state1 = ((grp_nbreadreq_fu_94_p7 == 1'd1) & (pi_fsm_state == 2'd2));
end

always @ (*) begin
    ap_predicate_op33_read_state1 = (~(pi_fsm_state == 2'd2) & ~(pi_fsm_state == 2'd1) & (grp_nbreadreq_fu_94_p7 == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_write_state2 = ((tmp_2_reg_327 == 1'd1) & (pi_fsm_state_load_reg_323 == 2'd1));
end

always @ (*) begin
    ap_predicate_op64_write_state2 = (((((~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (ipProtocol_V_reg_355 == 8'd6)) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (ipProtocol_V_reg_355 == 8'd17))) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (ipProtocol_V_reg_355 == 8'd1))) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2048) & (tmp_reg_342 == 1'd1) & (icmp_ln1019_reg_359 == 1'd0))) | (~(pi_fsm_state_load_reg_323 == 2'd2) & ~(pi_fsm_state_load_reg_323 == 2'd1) & (ethernetType_V_reg_351 == 16'd2054) & (tmp_reg_342 == 1'd1)));
end

assign ap_ready = internal_ap_ready;

assign ethernetType_V_fu_223_p3 = {{tmp_5_i_fu_213_p4}, {tmp_4_i_fu_203_p4}};

assign grp_fu_175_p1 = s_axis_TLAST_int_regslice;

assign grp_nbreadreq_fu_94_p7 = s_axis_TVALID_int_regslice;

assign icmp_ln1019_fu_251_p2 = ((ipVersion_V_fu_231_p4 == 4'd4) ? 1'b1 : 1'b0);

assign ipProtocol_V_fu_241_p4 = {{s_axis_TDATA_int_regslice[191:184]}};

assign ipVersion_V_fu_231_p4 = {{s_axis_TDATA_int_regslice[119:116]}};

assign s_axis_TREADY = regslice_both_s_axis_V_data_V_U_ack_in;

assign select_ln235_fu_263_p3 = ((s_axis_TLAST_int_regslice[0:0] == 1'b1) ? 2'd0 : ap_phi_mux_storemerge_i_phi_fu_134_p4);

assign start_out = real_start;

assign tmp_4_i_fu_203_p4 = {{s_axis_TDATA_int_regslice[111:104]}};

assign tmp_5_i_fu_213_p4 = {{s_axis_TDATA_int_regslice[103:96]}};

assign tmp_6_i_fu_281_p6 = {{{{{tdest_r_V}, {7'd0}}, {tmp_last_V_1_reg_331}}, {reg_183}}, {reg_179}};

assign tmp_7_i_fu_305_p6 = {{{{{ap_phi_reg_pp0_iter1_tdest_5_ph_i_reg_142}, {7'd0}}, {tmp_last_V_reg_346}}, {reg_183}}, {reg_179}};

assign zext_ln228_fu_318_p1 = tmp_7_i_fu_305_p6;

assign zext_ln248_fu_294_p1 = tmp_6_i_fu_281_p6;

endmodule //packet_handler_packet_identification
